In [47]:
import pandas as pd

In [48]:
df = pd.read_csv("heart_disease.csv")

In [49]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   9971 non-null   float64
 1   Gender                9981 non-null   str
 2   Blood Pressure        9981 non-null   float64
 3   Cholesterol Level     9970 non-null   float64
 4   Exercise Habits       9975 non-null   str
 5   Smoking               9975 non-null   str
 6   Family Heart Disease  9979 non-null   str
 7   Diabetes              9970 non-null   str
 8   BMI                   9978 non-null   float64
 9   High Blood Pressure   9974 non-null   str
 10  Low HDL Cholesterol   9975 non-null   str
 11  High LDL Cholesterol  9974 non-null   str
 12  Alcohol Consumption   7414 non-null   str
 13  Stress Level          9978 non-null   str
 14  Sleep Hours           9975 non-null   float64
 15  Sugar Consumption     9970 non-null   str
 16  Triglyceride Level    9974 non-null   float64
 17  Fasting Blood Sugar   9978 non-null   float64
 18  CRP Level             9974 non-null   float64
 19  Homocysteine Level    9980 non-null   float64
 20  Heart Disease Status  10000 non-null  str
dtypes: float64(9), str(12)
memory usage: 1.6 MB

In [50]:
# to display every column
pd.set_option("display.max_columns",None)

In [51]:
df.head(10)

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,Male,153.0,155.0,High,Yes,Yes,No,24.991591,Yes,Yes,No,High,Medium,7.633228,Medium,342.0,NaN,12.969246,12.387250,No
1,69.0,Female,146.0,286.0,High,No,Yes,Yes,25.221799,No,Yes,No,Medium,High,8.744034,Medium,133.0,157.0,9.355389,19.298875,No
2,46.0,Male,126.0,216.0,Low,No,No,No,29.855447,No,Yes,Yes,Low,Low,4.440440,Low,393.0,92.0,12.709873,11.230926,No
3,32.0,Female,122.0,293.0,High,Yes,Yes,No,24.130477,Yes,No,Yes,Low,High,5.249405,High,293.0,94.0,12.509046,5.961958,No
4,60.0,Male,166.0,242.0,Low,Yes,Yes,Yes,20.486289,Yes,No,No,Low,High,7.030971,High,263.0,154.0,10.381259,8.153887,No
5,25.0,Male,152.0,257.0,Low,Yes,No,No,28.144681,No,No,No,Low,Medium,5.504876,Low,126.0,91.0,4.297575,10.815983,No
6,78.0,Female,121.0,175.0,High,Yes,Yes,Yes,18.042332,No,Yes,No,Medium,Medium,9.240911,Medium,107.0,85.0,11.582983,19.659461,No
7,38.0,Female,161.0,187.0,Low,Yes,Yes,Yes,34.736683,No,No,No,Low,Medium,7.841008,High,228.0,111.0,4.929381,17.146599,No
8,56.0,Female,135.0,291.0,Low,No,Yes,Yes,34.493112,Yes,NaN,Yes,High,Low,6.941403,High,317.0,103.0,5.119015,6.051129,No
9,75.0,Male,144.0,252.0,Low,Yes,Yes,No,30.142149,No,No,Yes,Low,Medium,4.002662,High,199.0,96.0,10.005698,7.604357,No

In [52]:
df.isnull().sum()

Age                       29
Gender                    19
Blood Pressure            19
Cholesterol Level         30
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                       22
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours               25
Sugar Consumption         30
Triglyceride Level        26
Fasting Blood Sugar       22
CRP Level                 26
Homocysteine Level        20
Heart Disease Status       0
dtype: int64

## handling null-values

In [53]:
df.columns

Index(['Age', 'Gender', 'Blood Pressure', 'Cholesterol Level',
       'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'BMI',
       'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol',
       'Alcohol Consumption', 'Stress Level', 'Sleep Hours',
       'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar',
       'CRP Level', 'Homocysteine Level', 'Heart Disease Status'],
      dtype='str')

In [54]:
from sklearn.impute import SimpleImputer

### Select only ***str*** values

In [55]:
df.select_dtypes(include=["int64"]).columns

Index([], dtype='str')

In [56]:
# .tolist() is used to change column obj to list type

categorical_cols = df.select_dtypes(include=["str"]).columns.tolist()
numerical_cols = df.select_dtypes(include = ["float64"]).columns.tolist()

In [57]:
categorical_cols
numerical_cols

['Age',
 'Blood Pressure',
 'Cholesterol Level',
 'BMI',
 'Sleep Hours',
 'Triglyceride Level',
 'Fasting Blood Sugar',
 'CRP Level',
 'Homocysteine Level']

### replacing null-values

In [58]:
# find the median values of each col 
num_imputer = SimpleImputer(strategy="median")

In [59]:
# re-fill null-values of each col with respective col's median values
df[numerical_cols] = num_imputer.fit_transform(df[numerical_cols])

In [60]:
df.isnull().sum()

Age                        0
Gender                    19
Blood Pressure             0
Cholesterol Level          0
Exercise Habits           25
Smoking                   25
Family Heart Disease      21
Diabetes                  30
BMI                        0
High Blood Pressure       26
Low HDL Cholesterol       25
High LDL Cholesterol      26
Alcohol Consumption     2586
Stress Level              22
Sleep Hours                0
Sugar Consumption         30
Triglyceride Level         0
Fasting Blood Sugar        0
CRP Level                  0
Homocysteine Level         0
Heart Disease Status       0
dtype: int64

In [63]:
cat_imputer = SimpleImputer(strategy="most_frequent")
df[categorical_cols] = cat_imputer.fit_transform(df[categorical_cols])

In [65]:
df.isnull().sum()

Age                     0
Gender                  0
Blood Pressure          0
Cholesterol Level       0
Exercise Habits         0
Smoking                 0
Family Heart Disease    0
Diabetes                0
BMI                     0
High Blood Pressure     0
Low HDL Cholesterol     0
High LDL Cholesterol    0
Alcohol Consumption     0
Stress Level            0
Sleep Hours             0
Sugar Consumption       0
Triglyceride Level      0
Fasting Blood Sugar     0
CRP Level               0
Homocysteine Level      0
Heart Disease Status    0
dtype: int64

## Label Encoding

In [81]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Age                   10000 non-null  float64
 1   Gender                10000 non-null  str
 2   Blood Pressure        10000 non-null  float64
 3   Cholesterol Level     10000 non-null  float64
 4   Exercise Habits       10000 non-null  str
 5   Smoking               10000 non-null  str
 6   Family Heart Disease  10000 non-null  str
 7   Diabetes              10000 non-null  str
 8   BMI                   10000 non-null  float64
 9   High Blood Pressure   10000 non-null  str
 10  Low HDL Cholesterol   10000 non-null  str
 11  High LDL Cholesterol  10000 non-null  str
 12  Alcohol Consumption   10000 non-null  str
 13  Stress Level          10000 non-null  str
 14  Sleep Hours           10000 non-null  float64
 15  Sugar Consumption     10000 non-null  str
 16  Triglyceride Level    10000 non-null  float64
 17  Fasting Blood Sugar   10000 non-null  float64
 18  CRP Level             10000 non-null  float64
 19  Homocysteine Level    10000 non-null  float64
 20  Heart Disease Status  10000 non-null  str
dtypes: float64(9), str(12)
memory usage: 1.6 MB

In [83]:
categorical_cols

['Gender',
 'Exercise Habits',
 'Smoking',
 'Family Heart Disease',
 'Diabetes',
 'High Blood Pressure',
 'Low HDL Cholesterol',
 'High LDL Cholesterol',
 'Alcohol Consumption',
 'Stress Level',
 'Sugar Consumption',
 'Heart Disease Status']

## Label encoding using (sklearn LabelEncoder)

In [84]:
from sklearn.preprocessing import LabelEncoder

In [85]:
le = LabelEncoder()

In [88]:
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

In [89]:
df.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,1,153.0,155.0,0,1,1,0,24.991591,1,1,0,0,2,7.633228,2,342.0,120.0,12.969246,12.387250,0
1,69.0,0,146.0,286.0,0,0,1,1,25.221799,0,1,0,2,0,8.744034,2,133.0,157.0,9.355389,19.298875,0
2,46.0,1,126.0,216.0,1,0,0,0,29.855447,0,1,1,1,1,4.440440,1,393.0,92.0,12.709873,11.230926,0
3,32.0,0,122.0,293.0,0,1,1,0,24.130477,1,0,1,1,0,5.249405,0,293.0,94.0,12.509046,5.961958,0
4,60.0,1,166.0,242.0,1,1,1,1,20.486289,1,0,0,1,0,7.030971,0,263.0,154.0,10.381259,8.153887,0

## Model training

In [91]:
df.columns

Index(['Age', 'Gender', 'Blood Pressure', 'Cholesterol Level',
       'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'BMI',
       'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol',
       'Alcohol Consumption', 'Stress Level', 'Sleep Hours',
       'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar',
       'CRP Level', 'Homocysteine Level', 'Heart Disease Status'],
      dtype='str')

In [93]:
X = df.drop("Heart Disease Status", axis=1)
y = df["Heart Disease Status"]

In [96]:
from sklearn.model_selection import train_test_split

In [98]:
X_train , X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [99]:
from sklearn.ensemble import RandomForestClassifier

In [100]:
model = RandomForestClassifier()

In [101]:
model.fit(X_train,y_train)

RandomForestClassifier()

## Model Evaluation

In [103]:
from sklearn.metrics import accuracy_score, classification_report

In [104]:
y_cup = model.predict(X_test)

In [105]:
print(f"Accuracy score: {accuracy_score(y_test,y_cup)}")

Accuracy score: 0.801

In [106]:
print(f"Classification report:\n {classification_report(y_test,y_cup)}")

Classification report:
               precision    recall  f1-score   support

           0       0.80      1.00      0.89      1603
           1       0.00      0.00      0.00       397

    accuracy                           0.80      2000
   macro avg       0.40      0.50      0.44      2000
weighted avg       0.64      0.80      0.71      2000

## Model Testing

In [107]:
df.head()

,Age,Gender,Blood Pressure,Cholesterol Level,Exercise Habits,Smoking,Family Heart Disease,Diabetes,BMI,High Blood Pressure,Low HDL Cholesterol,High LDL Cholesterol,Alcohol Consumption,Stress Level,Sleep Hours,Sugar Consumption,Triglyceride Level,Fasting Blood Sugar,CRP Level,Homocysteine Level,Heart Disease Status
0,56.0,1,153.0,155.0,0,1,1,0,24.991591,1,1,0,0,2,7.633228,2,342.0,120.0,12.969246,12.387250,0
1,69.0,0,146.0,286.0,0,0,1,1,25.221799,0,1,0,2,0,8.744034,2,133.0,157.0,9.355389,19.298875,0
2,46.0,1,126.0,216.0,1,0,0,0,29.855447,0,1,1,1,1,4.440440,1,393.0,92.0,12.709873,11.230926,0
3,32.0,0,122.0,293.0,0,1,1,0,24.130477,1,0,1,1,0,5.249405,0,293.0,94.0,12.509046,5.961958,0
4,60.0,1,166.0,242.0,1,1,1,1,20.486289,1,0,0,1,0,7.030971,0,263.0,154.0,10.381259,8.153887,0

In [110]:
df.columns

Index(['Age', 'Gender', 'Blood Pressure', 'Cholesterol Level',
       'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'BMI',
       'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol',
       'Alcohol Consumption', 'Stress Level', 'Sleep Hours',
       'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar',
       'CRP Level', 'Homocysteine Level', 'Heart Disease Status'],
      dtype='str')

In [ ]:
survey_heading = []

for _ in X.columns:
    survey_heading.append(_)

print(survey_heading)

['Age', 'Gender', 'Blood Pressure', 'Cholesterol Level', 'Exercise Habits', 'Smoking', 'Family Heart Disease', 'Diabetes', 'BMI', 'High Blood Pressure', 'Low HDL Cholesterol', 'High LDL Cholesterol', 'Alcohol Consumption', 'Stress Level', 'Sleep Hours', 'Sugar Consumption', 'Triglyceride Level', 'Fasting Blood Sugar', 'CRP Level', 'Homocysteine Level']

In [124]:
def patient_survey(questions):
    ans = []
    for i in range(len(questions)):
        x = input(f"Your {questions[i]}")
        ans.append(x)

    return ans

p1 = patient_survey(survey_heading)

In [125]:

symptons = pd.DataFrame([p1], columns=X.columns)
status = model.predict(symptons)

In [126]:
if status[0] == 0:
    print("Patient has no disease")
else:
    print("Patient has heart disease")

Patient has no disease